#!/usr/bin/env bash
if [ -d /run/s6/container_environment ]; then
    for f in /run/s6/container_environment/*; do
        [ -f "$f" ] && export "$(basename "$f")"="$(cat "$f")"
    done
fi
exec /usr/bin/speedtest_runner.sh
