worker_processes 1;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 64;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log    /dev/stdout;
    sendfile      on;
    keepalive_timeout 65;

    server {
        listen 8099;
        root /var/www/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/results {
            alias /data/speedtest/results.json;
            add_header Content-Type application/json;
            add_header Cache-Control "no-cache, no-store";
            add_header Access-Control-Allow-Origin *;
        }

        location /api/config {
            alias /data/speedtest/config.json;
            add_header Content-Type application/json;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
